name: ci-cd for nodejs-project

on :
  push:
    branches:
      - sample
      - main
      - mas


jobs:

    build:
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v4

            - name: To install node.js version
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'

            - name: To install Build and test
              run: | 
                npm install
                npm run build --if-present
                npm run test --if-present

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                name: node-app
                path: .


    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: node-app

            - name: Run tests
              run: |
                npm install
                npm run test --if-present

    deploy:
        runs-on: ubuntu-latest
        needs: [build,test ]

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: node-app

            



  


            


