name: ci-cd for nodejs-project

on :
  #push:
  #  branches:
  #    - sample
  #    - main
  #    - mas

  pull_request:
    branches:
      - sample
      - main
      - mas

  schedule:
    - cron: '45 4 * * *' # Runs every day at midnight

  workflow_dispatch: # Allows manual triggering of the workflow


jobs:

    build:
        runs-on: ubuntu-latest


        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: log in to docker
              uses: azure/docker-login@v2
              with:
                login-server: sampledevuacr.azurecr.io
                username: sampledevuacr
                password: ${{ secrets.Azure_PASSWORD }}

            - name: build and push docker image
              run: |
                docker build -t sagarshiva0/nodejs-project:v4 .
                docker push sagarshiva0/nodejs-project:v4
                
                

  




            



  


            


